targets = [
  ["Squat", "Quads"],
  ["Squat", "Hamstrings"],
  ["Squat", "Calves"],
  ["Squat", "Lower Back"],
  ["Squat", "Glutes"],
  ["Squat", "Obliques"],
  ["Front Squat", "Quads"],
  ["Front Squat", "Hamstrings"],
  ["Front Squat", "Calves"],
  ["Front Squat", "Lower Back"],
  ["Front Squat", "Glutes"],
  ["Front Squat", "Forearms"],
  ["Front Squat", "Obliques"],
  ["Leg Press", "Quads"],
  ["Leg Curl", "Hamstrings"],
  ["45\xC2\xB0 Calf Press", "Calves"],
  ["Standing Calf Raise", "Calves"],
  ["Straight Leg Deadlift", "Hamstrings"],
  ["Straight Leg Deadlift", "Glutes"],
  ["Straight Leg Deadlift", "Lower Back"],
  ["Straight Leg Deadlift", "Forearms"],
  ["Straight Leg Deadlift", "Traps"],
  ["Barbell Curl", "Biceps"],
  ["Barbell Curl", "Forearms"],
  ["Dumbbell Curl", "Biceps"],
  ["Dumbbell Curl", "Forearms"],
  ["Hammer Curl", "Biceps"],
  ["Hammer Curl", "Forearms"],
  ["Seated Curl", "Biceps"],
  ["Seated Curl", "Forearms"],
  ["Cable Curl", "Biceps"],
  ["Close Grip Bench Press", "Triceps"],
  ["Close Grip Bench Press", "Chest"],
  ["Lying Tricep Extension", "Triceps"],
  ["Cable Pushdown", "Triceps"],
  ["Tricep Dip", "Triceps"],
  ["One Arm Tricep Extension", "Triceps"],
  ["Dumbbell Wrist Curl", "Forearms"],
  ["Military Press", "Anterior Delts"],
  ["Military Press", "Lateral Delts"],
  ["Military Press", "Posterior Delts"],
  ["Military Press", "Triceps"],
  ["Arnold Press", "Anterior Delts"],
  ["Arnold Press", "Lateral Delts"],
  ["Arnold Press", "Posterior Delts"],
  ["Arnold Press", "Triceps"],
  ["Dumbbell Shoulder Press", "Anterior Delts"],
  ["Dumbbell Shoulder Press", "Lateral Delts"],
  ["Dumbbell Shoulder Press", "Posterior Delts"],
  ["Dumbbell Shoulder Press", "Triceps"],
  ["Lateral Raise", "Lateral Delts"],
  ["Lateral Raise", "Forearms"],
  ["Upright Row", "Lats"],
  ["Upright Row", "Traps"],
  ["Barbell Shrug", "Traps"],
  ["Barbell Shrug", "Forearms"],
  ["Dumbbell Shrug", "Traps"],
  ["Dumbbell Shrug", "Forearms"],
  ["Deadlift", "Quads"],
  ["Deadlift", "Hamstrings"],
  ["Deadlift", "Glutes"],
  ["Deadlift", "Lower Back"],
  ["Deadlift", "Forearms"],
  ["Deadlift", "Traps"],
  ["Cable Pulldown", "Lats"],
  ["Cable Pulldown", "Biceps"],
  ["Pullup", "Lats"],
  ["Pullup", "Biceps"],
  ["Bent Over Row", "Lats"],
  ["Seated Cable Row", "Lats"],
  ["Good Morning", "Lower Back"],
  ["Good Morning", "Hamstrings"],
  ["Hyperextension", "Lower Back"],
  ["Barbell Bench Press", "Chest"],
  ["Barbell Bench Press", "Triceps"],
  ["Barbell Incline Bench Press", "Chest"],
  ["Barbell Incline Bench Press", "Anterior Delts"],
  ["Barbell Incline Bench Press", "Triceps"],
  ["Barbell Decline Bench Press", "Chest"],
  ["Barbell Decline Bench Press", "Triceps"],
  ["Dumbbell Bench Press", "Chest"],
  ["Dumbbell Bench Press", "Triceps"],
  ["Dumbbell Incline Bench Press", "Chest"],
  ["Dumbbell Incline Bench Press", "Anterior Delts"],
  ["Dumbbell Incline Bench Press", "Triceps"],
  ["Dumbbell Fly", "Chest"],
  ["Chest Dip", "Chest"],
  ["Incline Crunch", "Abdominals"],
  ["Incline Crunch", "Obliques"],
  ["Cable Kneeling Crunch", "Abdominals"],
  ["Cable Kneeling Crunch", "Obliques"],
  ["Leg Raise", "Abdominals"],
  ["Leg Raise", "Obliques"],
  ["Leg Raise", "Quads"],
  ["Overhead Squat", "Quads"],
  ["Overhead Squat", "Hamstrings"],
  ["Overhead Squat", "Calves"],
  ["Overhead Squat", "Lower Back"],
  ["Overhead Squat", "Glutes"],
  ["Overhead Squat", "Forearms"],
  ["Overhead Squat", "Obliques"],
  ["Muscle Up", "Chest"],
  ["Muscle Up", "Lats"],
  ["Muscle Up", "Biceps"],
  ["Muscle Up", "Triceps"],
  ["Muscle Up", "Forearms"],
  ["Muscle Up", "Anterior Delts"]
]

targets.each do |target|
  exercise, muscle = target
  default_user = User.find_by(email: "default_user@test.com")  

  Target.find_or_create_by!(
    exercise: Exercise.find_by(name: exercise, user: default_user),
    muscle: Muscle.find_by(name: muscle, user: default_user)
  )
end
